plugin:
  prefix: '&2[&aMineral Contest&2] &r'
  enabled: '&ePlugin activé.'
  disabled: '&ePlugin désactivé.'
  only_player_command: "&cSeul un joueur peut utiliser cette commande."
  not_enough_args: "&cCommande incomplète..."
  no_such_args: "&cArgument inconnu..."
  no_such_team: "&cAucune équipe avec ce nom n'a été trouvée !"

arena:
  chest_block: 'CHEST'
  cooldown_min_seconds: 300
  cooldown_max_seconds: 600
  chest_removed: "&aCoffre d'arène supprimé."
  chest_placed: "&aCoffre d'arène placé."
  chest_not_placed: "&cLe coffre n'est pas encore placé."
  chest_location: "&aLe coffre est situé en: &e{LOCATION}"
  chest_available: "&aLe coffre d'arène est maintenant disponible ! Fais §e/arene §apour te téléporter."
  chest_unavailable: "&cLe coffre d'arène n'est pas disponible pour le moment."
  chest_in_use: "&cUn joueur est en train d'ouvrir le coffre d'arène !"
  chest_rewards:
    - material: DIAMOND
      min: 1
      max: 3
    - material: IRON_INGOT
      min: 10
      max: 15
    - material: GOLD_INGOT
      min: 3
      max: 7
    - material: EMERALD
      min: 0
      max: 4

game:
  duration_seconds: 300
  alerts:
    - 600
    - 300
    - 60
    - 30
    - 5
    - 4
    - 3
    - 2
    - 1

  max_players_per_team: 4

  teams:
    red:
      name: "Rouge"
      color: "RED"
      icon: "RED_WOOL"
    green:
      name: "Vert"
      color: "GREEN"
      icon: "GREEN_WOOL"
    blue:
      name: "Bleu"
      color: "BLUE"
      icon: "BLUE_WOOL"
    yellow:
      name: "Jaune"
      color: "YELLOW"
      icon: "YELLOW_WOOL"

  started: "&aLa partie a démarré !"
  ended: "&cLa partie est terminée !"
  reset: "&7La partie a été réinitialisée."

drop:
  min_interval_seconds: 300
  max_interval_seconds: 900
  chest_placed: "&6Un drop est apparu en &e{X}&6, &e{Y}&6, &e{Z}&6 !"
  loot:
    - material: DIAMOND
      min: 2
      max: 6
    - material: IRON_INGOT
      min: 24
      max: 36
    - material: GOLD_INGOT
      min: 8
      max: 20
    - material: EMERALD
      min: 0
      max: 3