name: MineralContest
version: 1.0.0
author: ValaniDev
main: dev.valani.mineralcontest.Main
api-version: 21.1.1
commands:
  mineralcontest:
    aliases: [ mc ]
    description: "Default command for mineral contest"
  arenachest:
    aliases: [ ac ]
    description: "Gérer le coffre d'arène"
  kit:
    description: "Sélectionner un kit"
  team:
    description: "Sélectionner une équipe"
  c:
    description: "Commande de chat privé"
  arena:
    aliases: [ arene ]
    description: "Commande d'arène"
  admin:
    description: "Commande d'administration"
    permission: mineralcontest.admin
  start:
    description: "Démarrer une partie"
    permission: mineralcontest.start
  end:
    description: "Terminer une partie"
    permission: mineralcontest.end
  reset:
    description: "Réinitialiser la partie"
    permission: mineralcontest.reset